refactor: jar파일 전송 속도를 높이기 위한 rsync 도입

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -33,9 +33,9 @@ jobs:
           # EC2에서 기존 JAR 파일 삭제
           ssh -i weddy-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "rm -f /home/$EC2_USER/app/*.jar"
           
-          echo "Starting SCP transfer..."
-          timeout 480 scp -i weddy-key.pem -o StrictHostKeyChecking=no -v ./build/libs/weddy-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app/ || { echo "SCP failed"; exit 1; }
-          echo "SCP completed"
+          echo "Starting rsync transfer..."
+          timeout 480 rsync -avz --progress -e "ssh -i weddy-key.pem -o StrictHostKeyChecking=no" ./build/libs/weddy-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app/ || { echo "rsync failed"; exit 1; }
+          echo "rsync completed"
 
       - name: Deploy to EC2
         env:
